### ISSUE TITLE
Assign responsibility of purchases to moderators

### ISSUE THREAD

**Issue by rakshi00** [ElsaHilftDigital/main#15]
Drop-down list would be nice

**Comment by rakshi00** [comment]
Ideally, able to select and change moderator of several purchases (not essential)

**Comment by ntruessel** [comment]
Does assigning __all__ purchases of one moderator to another one work?

**Comment by rakshi00** [comment]
I'm pretty sure that there will be exceptions, so generally, no.
At least we would need "assign all purchase of one moderator to another" + "assign one purchase of one moderator to another", I guess.

**Comment by ntruessel** [comment]
Ok, so let's go with single assign first

**Comment by ntruessel** [comment]
:heavy_check_mark: Data Model

**Comment by ntruessel** [comment]
:heavy_check_mark: Backend
:heavy_check_mark: Frontend Display
