### ISSUE TITLE
Display receipt from DB

### ISSUE THREAD

**Issue by rakshi00** [ElsaHilftDigital/main#16]

**Comment by F1rst-Unicorn** [comment]
https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#probeContentType%28java.nio.file.Path%29

**Comment by F1rst-Unicorn** [comment]
Now we have `/api/v1/admin/purchases/{uuid}/receipt` which serves receipt images. Images always appear to be jpg, independent of uploaded format.
