### ISSUE TITLE
Migrate Existing Helpers

### ISSUE THREAD

**Issue by ntruessel** [ElsaHilftDigital/main#17]
It should be possible to import the current volunteers to the new system without them signing up again

**Comment by F1rst-Unicorn** [comment]
waiting for csv schema

**Comment by rakshi00** [comment]
Schema:

Name | Vorname | Adresse | PLZ | Wohnort | Geb.Dat. | IBAN | Bankname | Telefonnummer | Email

**Comment by F1rst-Unicorn** [comment]
Can you please check or clarify the following statements with them:

- [x] The IBAN is the empty string if and only if the vol wants no compensation

- [x] The birth date pattern is `dd.MM.yyyy`. So the string `01.01.1970` means the first of January in the year 1970. Please verify if the leading zero for padding is present/absent and if this is consistent

**Comment by rakshi00** [comment]
> Can you please check or clarify the following statements with them:
> 
> * [x]  The IBAN is the empty string if and only if the vol wants no compensation
> * [x]  The birth date pattern is `dd.MM.yyyy`. So the string `01.01.1970` means the first of January in the year 1970. Please verify if the leading zero for padding is present/absent and if this is consistent

@F1rst-Unicorn 
- There will be a separate column: compensation yes / no. We'll do 1 for yes, 0 for no (I can preformat)
- Assume all leading zeroes exist, I can preformat

**Comment by F1rst-Unicorn** [comment]
Ok, then the import can be done from backend perspective.

**Comment by rakshi00** [comment]
Import csv header will look like this:

Name | Vorname | Adresse | PLZ | Wohnort | Geb.Dat. | IBAN | Bankname | Entschädigung | Telefonnummer | Email

Do we need some front-end implementation for the import? It will be a one-time only thing.

**Comment by rakshi00** [comment]
Do we have the send e-mail functionality over sendgrid for the imported helpers?

**Comment by F1rst-Unicorn** [comment]
Yes, every helper will be processed the same way, no matter whether they signed up manually or were imported from the csv. so they will receive the email just the same

**Comment by ntruessel** [comment]
Do we handle duplicates?

**Comment by F1rst-Unicorn** [comment]
No, based on email?

**Comment by ntruessel** [comment]
I think we either have to manually scan for duplicates or implement something. Given this is a one time operation, we can opt for the manual removal of all pilot users

**Comment by rakshi00** [comment]
i can remove pilot users and duplicates

**Comment by F1rst-Unicorn** [comment]
> Do we need some front-end implementation for the import?

I'd say we pump it in via curl

**Comment by ntruessel** [comment]
Same, just make sure to use a protected endpoint

**Comment by rakshi00** [comment]
existing helpers should be set to confirmed directly after migration. Else, they would need to click through more than a hundred volunteers ^^'

**Comment by F1rst-Unicorn** [comment]
Embrace the power of curl^^

```
while read uuid ; do 
    curl -v "https://admin.elsa-hilft.ch/api/v1/admin/volunteers/$uuid/validate"
done
```

**Comment by rakshi00** [comment]
such awesomeness :D
