### ISSUE TITLE
Register from desktop

### ISSUE THREAD

**Issue by ntruessel** [ElsaHilftDigital/main#18]
When registering from a desktop browser, the user must get the signup link to his mobile device to be able to join the chat on telegram. The solution to this issue might be similar to the one for #17

**Comment by rakshi00** [comment]
The link actually works with Telegram Desktop as well. We could, in theory, ask user to install on the computer. It's not as clean a solution like a mail though.

**Comment by F1rst-Unicorn** [comment]
Mail code is there, mail account in cloud is missing
