### ISSUE TITLE
Enable export for purchase

### ISSUE THREAD

**Issue by rakshi00** [ElsaHilftDigital/main#39]
For volunteer: (10.- * amount of purchases not paid)
For customer: sum of all missing purchase costs (perhaps field "cost" missing in front-end, maybe we need a paid flag or we use the status for purchase)

**Comment by F1rst-Unicorn** [comment]
Suggested CSV for both volunteers (summing expenses and compensation) and customers:

```csv
date,shops,cost
2019-01-01,migros lidl aldi,10300
2019-01-02,migros,4200
```

These CSVs can be downloaded filtered by month. Do we keep the `PAYMENT_PENDING` state so moderators will have to move them to `PURCHASE_COMPLETED` explicitly? We could also remove this state and generate CSVs based on `paymentMethod != CASH`.

@rakshi00 thoughts?

**Comment by F1rst-Unicorn** [comment]
Only added endpoint for purchase export now

**Comment by rakshi00** [comment]
csv export schema https://gengs.sharepoint.com/:x:/s/VersusVirus/Eejr8i-m4p9Lo8ksgijaZc8Bek3qYTiiRhkveg0pvfH1rQ?e=H296h1
