### ISSUE TITLE
Redact data when deleted

### ISSUE THREAD

**Issue by rakshi00** [ElsaHilftDigital/main#43]
Volunteer
Customer

**Comment by rakshi00** [comment]
Prompt to display all steps to be taken before deleting volunteer / customer (e.g. pending payments).
Then redact everything.

**Comment by F1rst-Unicorn** [comment]
volunteer warning is done via telegram

**Comment by ntruessel** [comment]
What exactly is still required to be implemented here?

**Comment by F1rst-Unicorn** [comment]
If a moderator deletes a customer he must be informed that all money stuff relating that customer should be completed before really deleting the customer

**Comment by rakshi00** [comment]
I will also add a delete button to volunteer and customer detail

**Comment by ntruessel** [comment]
Data is redacted in the backend, buttons in the frontend are present
