### ISSUE TITLE
Telegram message Invokers in back-end long instead of Long

### ISSUE THREAD

**Issue by rakshi00** [ElsaHilftDigital/main#47]
e.g. VolunteerService.java line 78
`adminMessageSender.newHelperHasRegistered(organization.getTelegramModeratorGroupChatId()); fails on localhost as organization.getTelegramModeratorGroupChatId() is null and all functions have long parameters (instead of Long)

Null Pointer Exception when running in localhost

**Comment by F1rst-Unicorn** [comment]
Added migration to put dummy values in DEV as running the backend without these values doesn't make sense
