### ISSUE TITLE
Send Telegram message after volunteer confirms to be responsible for purchase

### ISSUE THREAD

**Issue by rakshi00** [ElsaHilftDigital/main#54]
Disable ja/nein after volunteer says "ja" and confirms
Send message:
"Vielen Dank für die Annahme des Auftrags. **Bitte schicke hier die Quittung, nachdem der Einkauf getätigt wurde.** Bei Fragen oder Unklarheiten kannst du dich jederzeit gerne hier melden. Danke für deinen Einsatz!"

**Comment by rakshi00** [comment]
Instead of "here", is link to the "real" Elsa (private) chat possible?

**Comment by F1rst-Unicorn** [comment]
This message will be sent in the private chat between assigned volunteer and bot. So if you want to link to the `"real" Elsa (private) chat` you want the message to link to the same chat itself?

**Comment by rakshi00** [comment]
> This message will be sent in the private chat between assigned volunteer and bot. So if you want to link to the `"real" Elsa (private) chat` you want the message to link to the same chat itself?

No, it should be a link to another user.
Currently, they are using one specific cellphone for the "real" Elsa account, which is not our bot. Is that even possible?
If yes, what do you need? the global username?

**Comment by F1rst-Unicorn** [comment]
Aha so from my view there is a dedicated telegram user to which I should link. This is easily possible, we just need the user's telegram id.

I would extend the `organization` db model to carry another global telegram id and link this to all messages which need such a link. Learning the telegram id is a bit of tinkering: I add some logging for unexpected messages and then the telegram user sends a message to the bot, just to learn the sender's telegram id. Then this id will be logged and I would manually enter it to the db.

I'll prepare what is needed and let you know once the telegram user can contact the bot

**Comment by F1rst-Unicorn** [comment]
The stuff described above is done. So once the (now denoted) telegram support user sends some text to the bot it will be logged and I can enter it into the DB. Keep me posted on when this happens

**Comment by rakshi00** [comment]
Would the easiest way be to on-board the telegram support as a normal volunteer to get the /start message?

**Comment by F1rst-Unicorn** [comment]
Not necessarily. The only difference is that I would extract the telegram user id from the DB instead of the log. But manual intervention would be needed anyway.

**Comment by F1rst-Unicorn** [comment]
Done by uubk by executing DB patch

**Comment by rakshi00** [comment]
![image](https://user-images.githubusercontent.com/14850875/80025912-9aedb880-84e1-11ea-8642-1501c60f8309.png)
is the link to "real" Elsa not yet on production?

**Comment by rakshi00** [comment]
![image](https://user-images.githubusercontent.com/14850875/80026596-af7e8080-84e2-11ea-9809-24a9c3ac07f7.png)
Same with confirmation message at end. Link does not seem to work :/

**Comment by F1rst-Unicorn** [comment]
The user id in the db is not valid. please make the "real" elsa send another personal message to the bot
