### ISSUE TITLE
Change bot logo to elsahilft_Baden.png

### ISSUE THREAD

**Issue by rakshi00** [ElsaHilftDigital/main#63]

**Comment by F1rst-Unicorn** [comment]
I found ElsaHilftMehr.ico in the Development team and Logos/ElsaHilftMehr2.png and Logos/ElsaHilftMehr.png in General. Which one do you mean?

**Comment by rakshi00** [comment]
It's elsahilft_Baden.png, it's already in the /public repository.

**Comment by rakshi00** [comment]
> I found ElsaHilftMehr.ico in the Development team and Logos/ElsaHilftMehr2.png and Logos/ElsaHilftMehr.png in General. Which one do you mean?

It's elsahilft_Baden.png, it's already in the /public repository.

**Comment by F1rst-Unicorn** [comment]
I only set the prod bot image to avoid confusion for testers. just reopen if you want the test bot to also carry the logo
