### ISSUE TITLE
Duplicate purchase with old customer when creating new purchase

### ISSUE THREAD

**Issue by rakshi00** [ElsaHilftDigital/main#80]
Only happens with some moderator accounts, e.g. "Philippe".
Timestamp and content of both purchases are identical. The purchase with the correct customer will also get created.

![image](https://user-images.githubusercontent.com/14850875/80348626-5ca02280-886e-11ea-8bf1-6016ae61522f.png)

**Comment by ntruessel** [comment]
Fixed
