### ISSUE TITLE
Add execution date for purchase

### ISSUE THREAD

**Issue by rakshi00** [ElsaHilftDigital/main#88]
Moderator can choose what execution date purchase has.
Purchase list is ordered by execution date instead of creation date.

**Comment by F1rst-Unicorn** [comment]
What is an execution? The publishing date or the date when the volunteer enters the shop? or delivery date?

**Comment by rakshi00** [comment]
The publishing date, the purchase date and the delivery date are all the same at the moment. We only provide the moderators with a field, so that the purchase is grouped at that date in the list view. They need to decide how they want to define it if either one of the dates you mentioned is different.

**Comment by rakshi00** [comment]
Purchase list should be sorted
1. according to red, yellow, green
2. according to execution date where newest first

**Comment by rakshi00** [comment]
Implemented, not fully tested yet
