### ISSUE TITLE
Upload multiple receipts

### ISSUE THREAD

**Issue by rakshi00** [ElsaHilftDigital/main#89]

**Comment by F1rst-Unicorn** [comment]
How should the user interaction look like? atm the volunteer uploads a picture and is offered open purchases to assign the picture to. The easiest way is to collect all pictures and offer an open purchase as long as it is in state `VOLUNTEER_ACCEPTED`.

On moderator side we issue a moderator chat message for each uploaded picture. But a moderator would have to determine in the frontend UI whether he has all receipts of the purchase to inform the customer and only then call the customer. If he switches to `PURCHASE_IN_DELIVERY` too early the volunteer cannot upload any receipts any more. Do you think this is reasonable?

**Comment by rakshi00** [comment]
Sounds good. The first paragraph is exactly how I imagined it.

I think the moderator needs to check by themselves. We only have a problem with th status change from `VOLUNTEER_ACCEPTED` to `PURCHASE_COMPLETED`. The easiest at them moment would be to change the status as soon as we receive one receipt. The moderator has to check afterwards if all receipts have been issued.

**Comment by F1rst-Unicorn** [comment]
uuuu, much better idea: we know the supermarkets per purchase, so we require them to upload as many receipts as there are supermarkets in the purchase. and in telegram we can print the supermarket name onto the button as well for correct attribution :D Or will this constrain us in some way?

**Comment by ntruessel** [comment]
Looks good

**Comment by ntruessel** [comment]
Will we switch to non-db stored files as well or will we keep them in the database for the moment?

**Comment by ntruessel** [comment]
Just make sure to account for user errors, as they will happen frequently

**Comment by rakshi00** [comment]
> uuuu, much better idea: we know the supermarkets per purchase, so we require them to upload as many receipts as there are supermarkets in the purchase. and in telegram we can print the supermarket name onto the button as well for correct attribution :D Or will this constrain us in some way?

Sounds good! I can imagine that in rare cases helpers upload a picture with more than one receipt. In that case they could upload twice?

**Comment by F1rst-Unicorn** [comment]
extracting images from DB is a separate issue #99

**Comment by rakshi00** [comment]
@F1rst-Unicorn 
Könnten wir dem PurchaseSupermarket auch eine UUID zuweisen, so dass wir über getReceipt statt UUID eines Purchases, die eines Supermarkets angeben?
Dann könnten wir die UUID im PurchaseSupermarketDTO dem FetchedPurchaseDTO weitergeben (für PurchaseDetail). Im Front-end baue ich eine Liste, bei dem jede Zeile ein Supermarkt ist und einen Button, um die Quittung des jeweiligen Supermarktes anzuzeigen. Dann kriegen wir das Bild wie gewohnt mit getReceipt, aber mit UUID vom Supermarket statt Purchase.

**Comment by F1rst-Unicorn** [comment]
that's the plan, yes. But I don't know by when I can do this, that's why i unassigned me

**Comment by rakshi00** [comment]
Alright, I‘m gonna try to implement it. Hopefully someone more skilled can then check if it‘s correct :P

**Comment by rakshi00** [comment]
@ntruessel @F1rst-Unicorn Just pushed my changes, hopefully it's comprehensive... Please have a look when you have time :)
what do we do with the supermarkets that don't have a UUID yet (already in DB)?
Also changed the export mechanics, hopefully it's alright.
