### ISSUE TITLE
Automatic refresh

### ISSUE THREAD

**Issue by rakshi00** [ElsaHilftDigital/main#91]

**Comment by rakshi00** [comment]
@ntruessel Could we just implement a history.push(.../{purchase-uuid}) to the respective purchase, so that the site refreshes after e.g. publish (so that status is updated etc.)?

**Comment by ntruessel** [comment]
This would definitively improve the current situation

**Comment by rakshi00** [comment]
sadly: "history cannot PUSH the same path;"

I'll go with `history.go(0);`
