### ISSUE TITLE
Properly Escape Support Chat

### ISSUE THREAD

**Issue by ntruessel** [ElsaHilftDigital/main#93]
The value from the `telegram_support_chat` DB field is not properly escaped when sent via telegram. This causes the messages to be rejected and the purchases to get stuck.

Example: Telegram handle containing underscores are recognized as italics instead of underscores.

**Comment by ntruessel** [comment]
Note: the release of this bugfix **must** be coordinated with database updates since this part of the configuration is stored in the database

**Comment by F1rst-Unicorn** [comment]
Aaaaaaah damn it -.-
