### ISSUE TITLE
Remove Database-Stored Configuration

### ISSUE THREAD

**Issue by ntruessel** [ElsaHilftDigital/main#96]
Storing environment specific information in the database leads to many complications and ultimately prevents us from deploying different dumps in different environments (e.g. deploy a production dump in staging to reproduce incidents)

**Comment by F1rst-Unicorn** [comment]
Now the configuration is part of the properties file. Note that when using a dump from a different instance you have to set the `organization.update_offset = 0` as this is mutable persistent state of the bot
